### ISSUE TITLE
ffmpeg fails with 'filtergraph matches no streams'

### ISSUE THREAD

**Issue by ichdasich** [tilmanmoser/bbb-video-download#20]
When re-encoding a set of recordings on my infrastructure, ~10% (41/384) fail with an ffmpeg error of the form:
```
Error: Command failed: ffmpeg -hide_banner -loglevel error -i ./tmp/datamnSOeW/slides.mp4 -i /mnt/processing/published/presentation/<id>-<timestamp>/deskshare/deskshare.webm -filter_complex "[1:v][0:v]scale2ref[d][v1];[v1][d]overlay=enable='between(t,1509.5,1529.7)'[v2];[v2][d]overlay=enable='between(t,1679.1,1734.5)'[v3];[v3][d]overlay=enable='between(t,1757.4,1968.3)'[v4];[v4][d]overlay=enable='between(t,1989.4,2004)'[v5];[v5][d]overlay=enable='between(t,2017.8,2293.4)'[v6];[v6][d]overlay=enable='between(t,2628.7,3113.1)'[v7];[v7][d]overlay=enable='between(t,3123.1,3262.8)'[v8];[v8][d]overlay=enable='between(t,3363.6,3391.8)'[v9]" -map '[v9]' -threads 1 ./tmp/datamnSOeW/presentation.tmp.mp4
Stream specifier 'd' in filtergraph description [1:v][0:v]scale2ref[d][v1];[v1][d]overlay=enable='between(t,663.7,857.7)'[v2];[v2][d]overlay=enable='between(t,1268.4,1329.9)'[v3];[v3][d]overlay=enable='between(t,1340.4,1643.9)'[v4];[v4][d]overlay=enable='between(t,2501,3434.3)'[v5] matches no streams.
```
The parameter of the error changes, see below:
```
HOST nostream # grep 'Stream specifier' *|uniq|grep -o '......matches no streams'|sort|uniq -c|sort -rn
     21 '[v3] matches no streams
      6 '[v5] matches no streams
      4 '[v4] matches no streams
      3 '[v8] matches no streams
      3 '[v6] matches no streams
      1 '[v9] matches no streams
      1 '[v7] matches no streams
      1 [v12] matches no streams
      1 [v11] matches no streams
```
I can share an affected recording outside of github, if it helps.

**Comment by tilmanmoser** [comment]
I'll have a look into this today, latest tomorrow.

**Comment by tilmanmoser** [comment]
Fixed in v1.1.1

**Comment by ichdasich** [comment]
Heho,

thank you for describing the failure mode. I just upgraded to 1.1.2 and gave it a test-run (with a new recording with multiple screenshares), but still have the process failing. Do you think that this is related, or shall i open a new issue? Processing of a video with just one screenshare went fine.

```
I, [2020-10-28T09:35:00.022852 #9634]  INFO -- : [AVFilterGraph @ 0x561264643840] No output pad can be associated to link label 'd2'.
I, [2020-10-28T09:35:00.022969 #9634]  INFO -- : Error initializing complex filters.
I, [2020-10-28T09:35:00.022994 #9634]  INFO -- : Invalid argument
I, [2020-10-28T09:35:00.025766 #9634]  INFO -- : [Error] Failed rendering downloable video for BBB presentation  {
I, [2020-10-28T09:35:00.025835 #9634]  INFO -- :   args: Namespace(input='/var/bigbluebutton/published/presentation/<meetingid>-<ts>', output='/var/bigbluebutton/published/presentation/<meetingid>-<ts>/video.mp4'),
I, [2020-10-28T09:35:00.025860 #9634]  INFO -- :   env: { chunksize: 25 },
I, [2020-10-28T09:35:00.025880 #9634]  INFO -- :   workdir: './tmp/datavmSobt'
I, [2020-10-28T09:35:00.025907 #9634]  INFO -- : } Error: Command failed: ffmpeg -hide_banner -loglevel error -i ./tmp/datavmSobt/slides.mp4 -i /var/bigbluebutton/published/presentation/<meetingid>-<ts>/deskshare/deskshare.webm -filter_complex_script ./tmp/datavmSobt/filters.txt -map '[v4]' -threads 1 -strict -2 ./tmp/datavmSobt/presentation.tmp.mp4
I, [2020-10-28T09:35:00.025937 #9634]  INFO -- : [AVFilterGraph @ 0x561264643840] No output pad can be associated to link label 'd2'.
I, [2020-10-28T09:35:00.025968 #9634]  INFO -- : Error initializing complex filters.
I, [2020-10-28T09:35:00.025994 #9634]  INFO -- : Invalid argument
I, [2020-10-28T09:35:00.026021 #9634]  INFO -- :
I, [2020-10-28T09:35:00.026049 #9634]  INFO -- :     at checkExecSyncError (child_process.js:630:11)
I, [2020-10-28T09:35:00.026075 #9634]  INFO -- :     at Object.execSync (child_process.js:666:15)
I, [2020-10-28T09:35:00.026101 #9634]  INFO -- :     at combinedSlidesAndDeskshares (/opt/bbb-video-download/modules/presentation.js:53:18)
I, [2020-10-28T09:35:00.026142 #9634]  INFO -- :     at module.exports.createPresentationVideo (/opt/bbb-video-download/modules/presentation.js:22:18)
I, [2020-10-28T09:35:00.026170 #9634]  INFO -- :     at async module.exports.createVideo (/opt/bbb-video-download/modules/processor.js:20:26)
I, [2020-10-28T09:35:00.026197 #9634]  INFO -- :     at async run (/opt/bbb-video-download/index.js:10:9) {
I, [2020-10-28T09:35:00.026223 #9634]  INFO -- :   status: 1,
I, [2020-10-28T09:35:00.026250 #9634]  INFO -- :   signal: null,
I, [2020-10-28T09:35:00.026277 #9634]  INFO -- :   output: [
I, [2020-10-28T09:35:00.026306 #9634]  INFO -- :     null,
I, [2020-10-28T09:35:00.026328 #9634]  INFO -- :     <Buffer >,
I, [2020-10-28T09:35:00.026347 #9634]  INFO -- :     <Buffer 5b 41 56 46 69 6c 74 65 72 47 72 61 70 68 20 40 20 30 78 35 36 31 32 36 34 36 34 33 38 34 30 5d 20 4e 6f 20 6f 75 74 70 75 74 20 70 61 64 20 63 61 6e ... 88 more bytes>
I, [2020-10-28T09:35:00.026367 #9634]  INFO -- :   ],
I, [2020-10-28T09:35:00.026401 #9634]  INFO -- :   pid: 9951,
I, [2020-10-28T09:35:00.026424 #9634]  INFO -- :   stdout: <Buffer >,
I, [2020-10-28T09:35:00.026448 #9634]  INFO -- :   stderr: <Buffer 5b 41 56 46 69 6c 74 65 72 47 72 61 70 68 20 40 20 30 78 35 36 31 32 36 34 36 34 33 38 34 30 5d 20 4e 6f 20 6f 75 74 70 75 74 20 70 61 64 20 63 61 6e ... 88 more bytes>
I, [2020-10-28T09:35:00.026501 #9634]  INFO -- : }
```

**Comment by ichdasich** [comment]
Ok, scratch the 'processing went fine'; In the processed video, slides and drawings are also missing.

**Comment by tilmanmoser** [comment]
Ok. This is related to the scaling of the deskshare video. Can you provide the raw data? I tested it with various presentations that I have available, but apparently my testdata is lacking cases.

**Comment by ichdasich** [comment]
Can you drop me an email to t.fiebig@tudelft.nl? I can then give you links to two failing presentations.
